name: Secrets Demo

on: workflow_dispatch

jobs:
  secret-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Secret
        run: echo "The secret is set: ${{ secrets.MY_SECRET_MESSAGE != '' }}"

      - name: Use Secret as Env
        env:
          SECRET_MSG: ${{ secrets.MY_SECRET_MESSAGE }}
        run: echo "Secret loaded successfully"
